services:
  configserver:
   image: marcar30328675/configserver:latest
   mem_limit: 800m
   ports:
      - "8085:8085"
   networks:
      - aleal-network-macvlan	

  eurekaserver:
    image: marcar30328675/eurekaserver:latest
    mem_limit: 800m
    ports:
      - "8065:8065"
    networks:
      - aleal-network-macvlan
    depends_on: 
      - configservice
    deploy:
     restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 10
      window: 120s
    environment:
     SPRING_PROFILES_ACTIVE: dev
     #Se a単ade nuevamente ya que en ambientes reales las IP pueden cambiar, internamente se resuelve que esta se tome
     SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
      
  hotels:
    image: marcar30328675/hotels:latest
    hostname: hotels8080
    mem_limit: 800m
    ports:
      - "8080:8080"
    networks:
      - aleal-network-macvlan
    depends_on: 
      - configservice
      - eurekaserver
    deploy:
     restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 10
      window: 120s
    environment:
     SPRING_PROFILES_ACTIVE: dev
     #Se a単ade nuevamente ya que en ambientes reales las IP pueden cambiar, internamente se resuelve que esta se tome
     SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8065/eureka/
  rooms:
    image: marcar30328675/rooms:latest
    mem_limit: 800m
    ports:
      - "8081:8081"
    networks:
     aleal-network-macvlan:
      ipv4_address: 172.21.0.4
    depends_on: 
      - configservice
      - eurekaserver
    deploy:
     restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 10
      window: 120s
    environment:
     SPRING_PROFILES_ACTIVE: dev
     #Se a単ade nuevamente ya que en ambientes reales las IP pueden cambiar, internamente se resuelve que esta se tome
     SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8065/eureka/
  reservations:
    image: marcar30328675/reservations:latest
    mem_limit: 800m
    ports:
      - "8082:8082"
    networks:
      - aleal-network-macvlan
    depends_on: 
      - configservice
      - eurekaserver
    deploy:
     restart_policy:
      condition: on-failure
      delay: 10s
      max_attempts: 10
      window: 120s
    environment:
     SPRING_PROFILES_ACTIVE: dev
     #Se a単ade nuevamente ya que en ambientes reales las IP pueden cambiar, internamente se resuelve que esta se tome
     SPRING_CONFIG_IMPORT: configserver:http://configserver:8085
     EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8065/eureka/
networks:
 aleal-network-macvlan:
  driver: macvlan
  ipam:
   config:
   - subnet: 172.21.0.0/24
     gateway: 172.21.0.254